[pytest]
# Previne que o pytest tente varrer testes obsoletos e levante falsos negativos no Hook
addopts = 
    --ignore=tests/legacy
    --ignore=tests/data
    --ignore=tests/sandbox
    -v

# Path discovery base
testpaths =
    tests/unit
    tests/integration
    tests/e2e

# Configurações de asyncio para testes assíncronos
asyncio_mode = strict
asyncio_default_fixture_loop_scope = function
