"""Initial migration

Revision ID: 719d85e904f1
Revises: 
Create Date: 2026-02-27 00:19:15.562046

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '719d85e904f1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
