"""Add SensusDocumentModel

Revision ID: 7fc590802ed7
Revises: 719d85e904f1
Create Date: 2026-03-01 11:57:11.105785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fc590802ed7'
down_revision: Union[str, Sequence[str], None] = '719d85e904f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensus_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('frontmatter', sa.JSON(), nullable=True),
    sa.Column('extracted_todos', sa.JSON(), nullable=True),
    sa.Column('extracted_tags', sa.JSON(), nullable=True),
    sa.Column('extracted_links', sa.JSON(), nullable=True),
    sa.Column('vector_id', sa.String(length=100), nullable=True),
    sa.Column('semantic_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensus_documents_file_path'), 'sensus_documents', ['file_path'], unique=True)
    op.create_index(op.f('ix_sensus_documents_id'), 'sensus_documents', ['id'], unique=False)
    op.create_index(op.f('ix_sensus_documents_tenant_id'), 'sensus_documents', ['tenant_id'], unique=False)
    op.drop_table('system_settings_old')
    op.create_index(op.f('ix_chat_messages_tenant_id'), 'chat_messages', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_tenant_id'), 'chat_sessions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_document_cache_tenant_id'), 'document_cache', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    op.create_index(op.f('ix_system_settings_setting_key'), 'system_settings', ['setting_key'], unique=False)
    op.create_index(op.f('ix_system_settings_tenant_id'), 'system_settings', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_settings_tenant_id'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_setting_key'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_index(op.f('ix_document_cache_tenant_id'), table_name='document_cache')
    op.drop_index(op.f('ix_chat_sessions_tenant_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_messages_tenant_id'), table_name='chat_messages')
    op.create_table('system_settings_old',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('setting_key', sa.VARCHAR(length=100), nullable=False),
    sa.Column('setting_value', sa.TEXT(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('tenant_id', sa.VARCHAR(length=50), server_default=sa.text("'default'"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_sensus_documents_tenant_id'), table_name='sensus_documents')
    op.drop_index(op.f('ix_sensus_documents_id'), table_name='sensus_documents')
    op.drop_index(op.f('ix_sensus_documents_file_path'), table_name='sensus_documents')
    op.drop_table('sensus_documents')
    # ### end Alembic commands ###
