name: Frontend Web CI/CD

on:
  push:
    branches: [ "main" ]
    paths:
      - 'web-ui/**'
      - 'Dockerfile.web'
      - 'nginx.conf'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'web-ui/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-web

jobs:
  # Opcionalmente aguardar o status do Workflow DevSecOps FOSS via GitHub Actions UI logic, 
  # ou usar Reusable Workflows se fossem arquivos dependentes.
  # Para simplificar e rodar paralelo bloqueando pelo Branch Protection no GitHub:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        if: github.event_name == 'push'
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Vue Web Docker image
        uses: docker/build-push-action@v5
        if: github.event_name == 'push'
        with:
          context: .
          file: ./Dockerfile.web
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
